/* soapBusinessFunctionWebServiceSoapProxy.h
   Generated by gSOAP 2.8.3 from soapProxy.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapBusinessFunctionWebServiceSoapProxy_H
#define soapBusinessFunctionWebServiceSoapProxy_H
#include "soapH.h"
class BusinessFunctionWebServiceSoap
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'BusinessFunctionWebServiceSoap' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	BusinessFunctionWebServiceSoap()
	{ soap = soap_new(); endpoint = "http://220.165.8.124:2655/BusinessFunctionWebService.asmx"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://microsoft.com/wsdl/types/", NULL, NULL},
	{"ns10", "http://tempuri.org/HttpServiceSoap12", NULL, NULL},
	{"ns11", "http://tempuri.org/MobileWebServiceSoap", NULL, NULL},
	{"ns12", "http://tempuri.org/MobileWebServiceSoap12", NULL, NULL},
	{"ns13", "http://tempuri.org/BusinessFunctionWebServiceSoap", NULL, NULL},
	{"ns14", "http://tempuri.org/BusinessFunctionWebServiceSoap12", NULL, NULL},
	{"ns3", "http://tempuri.org/PaymentFunctionWebServiceSoap", NULL, NULL},
	{"ns4", "http://tempuri.org/PaymentFunctionWebServiceSoap12", NULL, NULL},
	{"ns5", "http://tempuri.org/UserFunctionWebServiceSoap", NULL, NULL},
	{"ns6", "http://tempuri.org/UserFunctionWebServiceSoap12", NULL, NULL},
	{"ns7", "http://tempuri.org/UtilFunctionWebServiceSoap", NULL, NULL},
	{"ns1", "http://tempuri.org/", NULL, NULL},
	{"ns8", "http://tempuri.org/UtilFunctionWebServiceSoap12", NULL, NULL},
	{"ns9", "http://tempuri.org/HttpServiceSoap", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~BusinessFunctionWebServiceSoap() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'BuyMiniCard' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__BuyMiniCard(_ns1__BuyMiniCard *ns1__BuyMiniCard, _ns1__BuyMiniCardResponse *ns1__BuyMiniCardResponse) { return soap ? soap_call___ns13__BuyMiniCard(soap, endpoint, NULL, ns1__BuyMiniCard, ns1__BuyMiniCardResponse) : SOAP_EOM; };
	/// Invoke 'GetPhoneNoByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetPhoneNoByCondition(_ns1__GetPhoneNoByCondition *ns1__GetPhoneNoByCondition, _ns1__GetPhoneNoByConditionResponse *ns1__GetPhoneNoByConditionResponse) { return soap ? soap_call___ns13__GetPhoneNoByCondition(soap, endpoint, NULL, ns1__GetPhoneNoByCondition, ns1__GetPhoneNoByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetMyNoSection' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetMyNoSection(_ns1__GetMyNoSection *ns1__GetMyNoSection, _ns1__GetMyNoSectionResponse *ns1__GetMyNoSectionResponse) { return soap ? soap_call___ns13__GetMyNoSection(soap, endpoint, NULL, ns1__GetMyNoSection, ns1__GetMyNoSectionResponse) : SOAP_EOM; };
	/// Invoke 'LockNo' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__LockNo(_ns1__LockNo *ns1__LockNo, _ns1__LockNoResponse *ns1__LockNoResponse) { return soap ? soap_call___ns13__LockNo(soap, endpoint, NULL, ns1__LockNo, ns1__LockNoResponse) : SOAP_EOM; };
	/// Invoke 'UnlockNo' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__UnlockNo(_ns1__UnlockNo *ns1__UnlockNo, _ns1__UnlockNoResponse *ns1__UnlockNoResponse) { return soap ? soap_call___ns13__UnlockNo(soap, endpoint, NULL, ns1__UnlockNo, ns1__UnlockNoResponse) : SOAP_EOM; };
	/// Invoke 'SubmitBusiness' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__SubmitBusiness(_ns1__SubmitBusiness *ns1__SubmitBusiness, _ns1__SubmitBusinessResponse *ns1__SubmitBusinessResponse) { return soap ? soap_call___ns13__SubmitBusiness(soap, endpoint, NULL, ns1__SubmitBusiness, ns1__SubmitBusinessResponse) : SOAP_EOM; };
	/// Invoke 'SellNo' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__SellNo(_ns1__SellNo *ns1__SellNo, _ns1__SellNoResponse *ns1__SellNoResponse) { return soap ? soap_call___ns13__SellNo(soap, endpoint, NULL, ns1__SellNo, ns1__SellNoResponse) : SOAP_EOM; };
	/// Invoke 'SellOhterCard' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__SellOhterCard(_ns1__SellOhterCard *ns1__SellOhterCard, _ns1__SellOhterCardResponse *ns1__SellOhterCardResponse) { return soap ? soap_call___ns13__SellOhterCard(soap, endpoint, NULL, ns1__SellOhterCard, ns1__SellOhterCardResponse) : SOAP_EOM; };
	/// Invoke 'GetMiniCardRecord' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetMiniCardRecord(_ns1__GetMiniCardRecord *ns1__GetMiniCardRecord, _ns1__GetMiniCardRecordResponse *ns1__GetMiniCardRecordResponse) { return soap ? soap_call___ns13__GetMiniCardRecord(soap, endpoint, NULL, ns1__GetMiniCardRecord, ns1__GetMiniCardRecordResponse) : SOAP_EOM; };
	/// Invoke 'GetPayMiniCardByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetPayMiniCardByCondition(_ns1__GetPayMiniCardByCondition *ns1__GetPayMiniCardByCondition, _ns1__GetPayMiniCardByConditionResponse *ns1__GetPayMiniCardByConditionResponse) { return soap ? soap_call___ns13__GetPayMiniCardByCondition(soap, endpoint, NULL, ns1__GetPayMiniCardByCondition, ns1__GetPayMiniCardByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetPayMiniCardHistoryByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetPayMiniCardHistoryByCondition(_ns1__GetPayMiniCardHistoryByCondition *ns1__GetPayMiniCardHistoryByCondition, _ns1__GetPayMiniCardHistoryByConditionResponse *ns1__GetPayMiniCardHistoryByConditionResponse) { return soap ? soap_call___ns13__GetPayMiniCardHistoryByCondition(soap, endpoint, NULL, ns1__GetPayMiniCardHistoryByCondition, ns1__GetPayMiniCardHistoryByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetPhoneNoItemByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetPhoneNoItemByCondition(_ns1__GetPhoneNoItemByCondition *ns1__GetPhoneNoItemByCondition, _ns1__GetPhoneNoItemByConditionResponse *ns1__GetPhoneNoItemByConditionResponse) { return soap ? soap_call___ns13__GetPhoneNoItemByCondition(soap, endpoint, NULL, ns1__GetPhoneNoItemByCondition, ns1__GetPhoneNoItemByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetPhoneNoItemAndHistoryByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetPhoneNoItemAndHistoryByCondition(_ns1__GetPhoneNoItemAndHistoryByCondition *ns1__GetPhoneNoItemAndHistoryByCondition, _ns1__GetPhoneNoItemAndHistoryByConditionResponse *ns1__GetPhoneNoItemAndHistoryByConditionResponse) { return soap ? soap_call___ns13__GetPhoneNoItemAndHistoryByCondition(soap, endpoint, NULL, ns1__GetPhoneNoItemAndHistoryByCondition, ns1__GetPhoneNoItemAndHistoryByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetCardService' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetCardService(_ns1__GetCardService *ns1__GetCardService, _ns1__GetCardServiceResponse *ns1__GetCardServiceResponse) { return soap ? soap_call___ns13__GetCardService(soap, endpoint, NULL, ns1__GetCardService, ns1__GetCardServiceResponse) : SOAP_EOM; };
	/// Invoke 'GetSellCardRecordByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetSellCardRecordByCondition(_ns1__GetSellCardRecordByCondition *ns1__GetSellCardRecordByCondition, _ns1__GetSellCardRecordByConditionResponse *ns1__GetSellCardRecordByConditionResponse) { return soap ? soap_call___ns13__GetSellCardRecordByCondition(soap, endpoint, NULL, ns1__GetSellCardRecordByCondition, ns1__GetSellCardRecordByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetSellCardRecordHistoryByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetSellCardRecordHistoryByCondition(_ns1__GetSellCardRecordHistoryByCondition *ns1__GetSellCardRecordHistoryByCondition, _ns1__GetSellCardRecordHistoryByConditionResponse *ns1__GetSellCardRecordHistoryByConditionResponse) { return soap ? soap_call___ns13__GetSellCardRecordHistoryByCondition(soap, endpoint, NULL, ns1__GetSellCardRecordHistoryByCondition, ns1__GetSellCardRecordHistoryByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetBusinessRecordByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetBusinessRecordByCondition(_ns1__GetBusinessRecordByCondition *ns1__GetBusinessRecordByCondition, _ns1__GetBusinessRecordByConditionResponse *ns1__GetBusinessRecordByConditionResponse) { return soap ? soap_call___ns13__GetBusinessRecordByCondition(soap, endpoint, NULL, ns1__GetBusinessRecordByCondition, ns1__GetBusinessRecordByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GettBusinessRecordHistoryByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GettBusinessRecordHistoryByCondition(_ns1__GettBusinessRecordHistoryByCondition *ns1__GettBusinessRecordHistoryByCondition, _ns1__GettBusinessRecordHistoryByConditionResponse *ns1__GettBusinessRecordHistoryByConditionResponse) { return soap ? soap_call___ns13__GettBusinessRecordHistoryByCondition(soap, endpoint, NULL, ns1__GettBusinessRecordHistoryByCondition, ns1__GettBusinessRecordHistoryByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetSellOtherCardRecordByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetSellOtherCardRecordByCondition(_ns1__GetSellOtherCardRecordByCondition *ns1__GetSellOtherCardRecordByCondition, _ns1__GetSellOtherCardRecordByConditionResponse *ns1__GetSellOtherCardRecordByConditionResponse) { return soap ? soap_call___ns13__GetSellOtherCardRecordByCondition(soap, endpoint, NULL, ns1__GetSellOtherCardRecordByCondition, ns1__GetSellOtherCardRecordByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GettSellOtherCardRecordHistoryByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GettSellOtherCardRecordHistoryByCondition(_ns1__GettSellOtherCardRecordHistoryByCondition *ns1__GettSellOtherCardRecordHistoryByCondition, _ns1__GettSellOtherCardRecordHistoryByConditionResponse *ns1__GettSellOtherCardRecordHistoryByConditionResponse) { return soap ? soap_call___ns13__GettSellOtherCardRecordHistoryByCondition(soap, endpoint, NULL, ns1__GettSellOtherCardRecordHistoryByCondition, ns1__GettSellOtherCardRecordHistoryByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetOtherCardList' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetOtherCardList(_ns1__GetOtherCardList *ns1__GetOtherCardList, _ns1__GetOtherCardListResponse *ns1__GetOtherCardListResponse) { return soap ? soap_call___ns13__GetOtherCardList(soap, endpoint, NULL, ns1__GetOtherCardList, ns1__GetOtherCardListResponse) : SOAP_EOM; };
	/// Invoke 'GetStockCardItemByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetStockCardItemByCondition(_ns1__GetStockCardItemByCondition *ns1__GetStockCardItemByCondition, _ns1__GetStockCardItemByConditionResponse *ns1__GetStockCardItemByConditionResponse) { return soap ? soap_call___ns13__GetStockCardItemByCondition(soap, endpoint, NULL, ns1__GetStockCardItemByCondition, ns1__GetStockCardItemByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetStockCardItemAndHistoryByCondition' of service 'BusinessFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns13__GetStockCardItemAndHistoryByCondition(_ns1__GetStockCardItemAndHistoryByCondition *ns1__GetStockCardItemAndHistoryByCondition, _ns1__GetStockCardItemAndHistoryByConditionResponse *ns1__GetStockCardItemAndHistoryByConditionResponse) { return soap ? soap_call___ns13__GetStockCardItemAndHistoryByCondition(soap, endpoint, NULL, ns1__GetStockCardItemAndHistoryByCondition, ns1__GetStockCardItemAndHistoryByConditionResponse) : SOAP_EOM; };
};
#endif
