/* soapUserFunctionWebServiceSoapProxy.h
   Generated by gSOAP 2.8.3 from soapProxy.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapUserFunctionWebServiceSoapProxy_H
#define soapUserFunctionWebServiceSoapProxy_H
#include "soapH.h"
class UserFunctionWebServiceSoap
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'UserFunctionWebServiceSoap' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	UserFunctionWebServiceSoap()
	{ soap = soap_new(); endpoint = "http://220.165.8.124:2655/UserFunctionWebService.asmx"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://microsoft.com/wsdl/types/", NULL, NULL},
	{"ns10", "http://tempuri.org/HttpServiceSoap12", NULL, NULL},
	{"ns11", "http://tempuri.org/MobileWebServiceSoap", NULL, NULL},
	{"ns12", "http://tempuri.org/MobileWebServiceSoap12", NULL, NULL},
	{"ns13", "http://tempuri.org/BusinessFunctionWebServiceSoap", NULL, NULL},
	{"ns14", "http://tempuri.org/BusinessFunctionWebServiceSoap12", NULL, NULL},
	{"ns3", "http://tempuri.org/PaymentFunctionWebServiceSoap", NULL, NULL},
	{"ns4", "http://tempuri.org/PaymentFunctionWebServiceSoap12", NULL, NULL},
	{"ns5", "http://tempuri.org/UserFunctionWebServiceSoap", NULL, NULL},
	{"ns6", "http://tempuri.org/UserFunctionWebServiceSoap12", NULL, NULL},
	{"ns7", "http://tempuri.org/UtilFunctionWebServiceSoap", NULL, NULL},
	{"ns1", "http://tempuri.org/", NULL, NULL},
	{"ns8", "http://tempuri.org/UtilFunctionWebServiceSoap12", NULL, NULL},
	{"ns9", "http://tempuri.org/HttpServiceSoap", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~UserFunctionWebServiceSoap() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'HelloWorld' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__HelloWorld(_ns1__HelloWorld *ns1__HelloWorld, _ns1__HelloWorldResponse *ns1__HelloWorldResponse) { return soap ? soap_call___ns5__HelloWorld(soap, endpoint, NULL, ns1__HelloWorld, ns1__HelloWorldResponse) : SOAP_EOM; };
	/// Invoke 'loggout' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__loggout(_ns1__loggout *ns1__loggout, _ns1__loggoutResponse *ns1__loggoutResponse) { return soap ? soap_call___ns5__loggout(soap, endpoint, NULL, ns1__loggout, ns1__loggoutResponse) : SOAP_EOM; };
	/// Invoke 'TestLogin' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__TestLogin(_ns1__TestLogin *ns1__TestLogin, _ns1__TestLoginResponse *ns1__TestLoginResponse) { return soap ? soap_call___ns5__TestLogin(soap, endpoint, NULL, ns1__TestLogin, ns1__TestLoginResponse) : SOAP_EOM; };
	/// Invoke 'GetUserInfo' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__GetUserInfo(_ns1__GetUserInfo *ns1__GetUserInfo, _ns1__GetUserInfoResponse *ns1__GetUserInfoResponse) { return soap ? soap_call___ns5__GetUserInfo(soap, endpoint, NULL, ns1__GetUserInfo, ns1__GetUserInfoResponse) : SOAP_EOM; };
	/// Invoke 'RegisterUser' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__RegisterUser(_ns1__RegisterUser *ns1__RegisterUser, _ns1__RegisterUserResponse *ns1__RegisterUserResponse) { return soap ? soap_call___ns5__RegisterUser(soap, endpoint, NULL, ns1__RegisterUser, ns1__RegisterUserResponse) : SOAP_EOM; };
	/// Invoke 'AlterPsw' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__AlterPsw(_ns1__AlterPsw *ns1__AlterPsw, _ns1__AlterPswResponse *ns1__AlterPswResponse) { return soap ? soap_call___ns5__AlterPsw(soap, endpoint, NULL, ns1__AlterPsw, ns1__AlterPswResponse) : SOAP_EOM; };
	/// Invoke 'AlterUserInfo' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__AlterUserInfo(_ns1__AlterUserInfo *ns1__AlterUserInfo, _ns1__AlterUserInfoResponse *ns1__AlterUserInfoResponse) { return soap ? soap_call___ns5__AlterUserInfo(soap, endpoint, NULL, ns1__AlterUserInfo, ns1__AlterUserInfoResponse) : SOAP_EOM; };
	/// Invoke 'AddAcountPayment' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__AddAcountPayment(_ns1__AddAcountPayment *ns1__AddAcountPayment, _ns1__AddAcountPaymentResponse *ns1__AddAcountPaymentResponse) { return soap ? soap_call___ns5__AddAcountPayment(soap, endpoint, NULL, ns1__AddAcountPayment, ns1__AddAcountPaymentResponse) : SOAP_EOM; };
	/// Invoke 'GetReturnInfo' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__GetReturnInfo(_ns1__GetReturnInfo *ns1__GetReturnInfo, _ns1__GetReturnInfoResponse *ns1__GetReturnInfoResponse) { return soap ? soap_call___ns5__GetReturnInfo(soap, endpoint, NULL, ns1__GetReturnInfo, ns1__GetReturnInfoResponse) : SOAP_EOM; };
	/// Invoke 'CharegeReturnedMoney' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__CharegeReturnedMoney(_ns1__CharegeReturnedMoney *ns1__CharegeReturnedMoney, _ns1__CharegeReturnedMoneyResponse *ns1__CharegeReturnedMoneyResponse) { return soap ? soap_call___ns5__CharegeReturnedMoney(soap, endpoint, NULL, ns1__CharegeReturnedMoney, ns1__CharegeReturnedMoneyResponse) : SOAP_EOM; };
	/// Invoke 'GetWorkNameList' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__GetWorkNameList(_ns1__GetWorkNameList *ns1__GetWorkNameList, _ns1__GetWorkNameListResponse *ns1__GetWorkNameListResponse) { return soap ? soap_call___ns5__GetWorkNameList(soap, endpoint, NULL, ns1__GetWorkNameList, ns1__GetWorkNameListResponse) : SOAP_EOM; };
	/// Invoke 'GetUserFunction' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__GetUserFunction(_ns1__GetUserFunction *ns1__GetUserFunction, _ns1__GetUserFunctionResponse *ns1__GetUserFunctionResponse) { return soap ? soap_call___ns5__GetUserFunction(soap, endpoint, NULL, ns1__GetUserFunction, ns1__GetUserFunctionResponse) : SOAP_EOM; };
	/// Invoke 'GetReturnRecord' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__GetReturnRecord(_ns1__GetReturnRecord *ns1__GetReturnRecord, _ns1__GetReturnRecordResponse *ns1__GetReturnRecordResponse) { return soap ? soap_call___ns5__GetReturnRecord(soap, endpoint, NULL, ns1__GetReturnRecord, ns1__GetReturnRecordResponse) : SOAP_EOM; };
	/// Invoke 'GetReturnRecordDeal' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__GetReturnRecordDeal(_ns1__GetReturnRecordDeal *ns1__GetReturnRecordDeal, _ns1__GetReturnRecordDealResponse *ns1__GetReturnRecordDealResponse) { return soap ? soap_call___ns5__GetReturnRecordDeal(soap, endpoint, NULL, ns1__GetReturnRecordDeal, ns1__GetReturnRecordDealResponse) : SOAP_EOM; };
	/// Invoke 'GetAcountPaymentRecord' of service 'UserFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns5__GetAcountPaymentRecord(_ns1__GetAcountPaymentRecord *ns1__GetAcountPaymentRecord, _ns1__GetAcountPaymentRecordResponse *ns1__GetAcountPaymentRecordResponse) { return soap ? soap_call___ns5__GetAcountPaymentRecord(soap, endpoint, NULL, ns1__GetAcountPaymentRecord, ns1__GetAcountPaymentRecordResponse) : SOAP_EOM; };
};
#endif
