/* soapUtilFunctionWebServiceSoapProxy.h
   Generated by gSOAP 2.8.3 from soapProxy.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapUtilFunctionWebServiceSoapProxy_H
#define soapUtilFunctionWebServiceSoapProxy_H
#include "soapH.h"
class UtilFunctionWebServiceSoap
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'UtilFunctionWebServiceSoap' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	UtilFunctionWebServiceSoap()
	{ soap = soap_new(); endpoint = "http://220.165.8.124:2655/UtilFunctionWebService.asmx"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://microsoft.com/wsdl/types/", NULL, NULL},
	{"ns10", "http://tempuri.org/HttpServiceSoap12", NULL, NULL},
	{"ns11", "http://tempuri.org/MobileWebServiceSoap", NULL, NULL},
	{"ns12", "http://tempuri.org/MobileWebServiceSoap12", NULL, NULL},
	{"ns13", "http://tempuri.org/BusinessFunctionWebServiceSoap", NULL, NULL},
	{"ns14", "http://tempuri.org/BusinessFunctionWebServiceSoap12", NULL, NULL},
	{"ns3", "http://tempuri.org/PaymentFunctionWebServiceSoap", NULL, NULL},
	{"ns4", "http://tempuri.org/PaymentFunctionWebServiceSoap12", NULL, NULL},
	{"ns5", "http://tempuri.org/UserFunctionWebServiceSoap", NULL, NULL},
	{"ns6", "http://tempuri.org/UserFunctionWebServiceSoap12", NULL, NULL},
	{"ns7", "http://tempuri.org/UtilFunctionWebServiceSoap", NULL, NULL},
	{"ns1", "http://tempuri.org/", NULL, NULL},
	{"ns8", "http://tempuri.org/UtilFunctionWebServiceSoap12", NULL, NULL},
	{"ns9", "http://tempuri.org/HttpServiceSoap", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~UtilFunctionWebServiceSoap() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'GetDicContentByCondition' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetDicContentByCondition(_ns1__GetDicContentByCondition *ns1__GetDicContentByCondition, _ns1__GetDicContentByConditionResponse *ns1__GetDicContentByConditionResponse) { return soap ? soap_call___ns7__GetDicContentByCondition(soap, endpoint, NULL, ns1__GetDicContentByCondition, ns1__GetDicContentByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetAllCategory' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetAllCategory(_ns1__GetAllCategory *ns1__GetAllCategory, _ns1__GetAllCategoryResponse *ns1__GetAllCategoryResponse) { return soap ? soap_call___ns7__GetAllCategory(soap, endpoint, NULL, ns1__GetAllCategory, ns1__GetAllCategoryResponse) : SOAP_EOM; };
	/// Invoke 'InsertDicContent' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__InsertDicContent(_ns1__InsertDicContent *ns1__InsertDicContent, _ns1__InsertDicContentResponse *ns1__InsertDicContentResponse) { return soap ? soap_call___ns7__InsertDicContent(soap, endpoint, NULL, ns1__InsertDicContent, ns1__InsertDicContentResponse) : SOAP_EOM; };
	/// Invoke 'UpdateDicContent' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__UpdateDicContent(_ns1__UpdateDicContent *ns1__UpdateDicContent, _ns1__UpdateDicContentResponse *ns1__UpdateDicContentResponse) { return soap ? soap_call___ns7__UpdateDicContent(soap, endpoint, NULL, ns1__UpdateDicContent, ns1__UpdateDicContentResponse) : SOAP_EOM; };
	/// Invoke 'DeleteDicContent' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__DeleteDicContent(_ns1__DeleteDicContent *ns1__DeleteDicContent, _ns1__DeleteDicContentResponse *ns1__DeleteDicContentResponse) { return soap ? soap_call___ns7__DeleteDicContent(soap, endpoint, NULL, ns1__DeleteDicContent, ns1__DeleteDicContentResponse) : SOAP_EOM; };
	/// Invoke 'UpdateDicContentByCategory' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__UpdateDicContentByCategory(_ns1__UpdateDicContentByCategory *ns1__UpdateDicContentByCategory, _ns1__UpdateDicContentByCategoryResponse *ns1__UpdateDicContentByCategoryResponse) { return soap ? soap_call___ns7__UpdateDicContentByCategory(soap, endpoint, NULL, ns1__UpdateDicContentByCategory, ns1__UpdateDicContentByCategoryResponse) : SOAP_EOM; };
	/// Invoke 'GetFunctionList' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetFunctionList(_ns1__GetFunctionList *ns1__GetFunctionList, _ns1__GetFunctionListResponse *ns1__GetFunctionListResponse) { return soap ? soap_call___ns7__GetFunctionList(soap, endpoint, NULL, ns1__GetFunctionList, ns1__GetFunctionListResponse) : SOAP_EOM; };
	/// Invoke 'UpdateUserFunctionList' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__UpdateUserFunctionList(_ns1__UpdateUserFunctionList *ns1__UpdateUserFunctionList, _ns1__UpdateUserFunctionListResponse *ns1__UpdateUserFunctionListResponse) { return soap ? soap_call___ns7__UpdateUserFunctionList(soap, endpoint, NULL, ns1__UpdateUserFunctionList, ns1__UpdateUserFunctionListResponse) : SOAP_EOM; };
	/// Invoke 'UpdateFunctionRight' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__UpdateFunctionRight(_ns1__UpdateFunctionRight *ns1__UpdateFunctionRight, _ns1__UpdateFunctionRightResponse *ns1__UpdateFunctionRightResponse) { return soap ? soap_call___ns7__UpdateFunctionRight(soap, endpoint, NULL, ns1__UpdateFunctionRight, ns1__UpdateFunctionRightResponse) : SOAP_EOM; };
	/// Invoke 'GetTableStatistics' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetTableStatistics(_ns1__GetTableStatistics *ns1__GetTableStatistics, _ns1__GetTableStatisticsResponse *ns1__GetTableStatisticsResponse) { return soap ? soap_call___ns7__GetTableStatistics(soap, endpoint, NULL, ns1__GetTableStatistics, ns1__GetTableStatisticsResponse) : SOAP_EOM; };
	/// Invoke 'GetNoticeList' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetNoticeList(_ns1__GetNoticeList *ns1__GetNoticeList, _ns1__GetNoticeListResponse *ns1__GetNoticeListResponse) { return soap ? soap_call___ns7__GetNoticeList(soap, endpoint, NULL, ns1__GetNoticeList, ns1__GetNoticeListResponse) : SOAP_EOM; };
	/// Invoke 'GetNoticeListByCondition' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetNoticeListByCondition(_ns1__GetNoticeListByCondition *ns1__GetNoticeListByCondition, _ns1__GetNoticeListByConditionResponse *ns1__GetNoticeListByConditionResponse) { return soap ? soap_call___ns7__GetNoticeListByCondition(soap, endpoint, NULL, ns1__GetNoticeListByCondition, ns1__GetNoticeListByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetNoticeItem' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetNoticeItem(_ns1__GetNoticeItem *ns1__GetNoticeItem, _ns1__GetNoticeItemResponse *ns1__GetNoticeItemResponse) { return soap ? soap_call___ns7__GetNoticeItem(soap, endpoint, NULL, ns1__GetNoticeItem, ns1__GetNoticeItemResponse) : SOAP_EOM; };
	/// Invoke 'GetAlertNoticeList' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetAlertNoticeList(_ns1__GetAlertNoticeList *ns1__GetAlertNoticeList, _ns1__GetAlertNoticeListResponse *ns1__GetAlertNoticeListResponse) { return soap ? soap_call___ns7__GetAlertNoticeList(soap, endpoint, NULL, ns1__GetAlertNoticeList, ns1__GetAlertNoticeListResponse) : SOAP_EOM; };
	/// Invoke 'AddNoticeItem' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__AddNoticeItem(_ns1__AddNoticeItem *ns1__AddNoticeItem, _ns1__AddNoticeItemResponse *ns1__AddNoticeItemResponse) { return soap ? soap_call___ns7__AddNoticeItem(soap, endpoint, NULL, ns1__AddNoticeItem, ns1__AddNoticeItemResponse) : SOAP_EOM; };
	/// Invoke 'AddNoticeItemToSomeone' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__AddNoticeItemToSomeone(_ns1__AddNoticeItemToSomeone *ns1__AddNoticeItemToSomeone, _ns1__AddNoticeItemToSomeoneResponse *ns1__AddNoticeItemToSomeoneResponse) { return soap ? soap_call___ns7__AddNoticeItemToSomeone(soap, endpoint, NULL, ns1__AddNoticeItemToSomeone, ns1__AddNoticeItemToSomeoneResponse) : SOAP_EOM; };
	/// Invoke 'UpdateNoticeItem' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__UpdateNoticeItem(_ns1__UpdateNoticeItem *ns1__UpdateNoticeItem, _ns1__UpdateNoticeItemResponse *ns1__UpdateNoticeItemResponse) { return soap ? soap_call___ns7__UpdateNoticeItem(soap, endpoint, NULL, ns1__UpdateNoticeItem, ns1__UpdateNoticeItemResponse) : SOAP_EOM; };
	/// Invoke 'DeleteNoticeItem' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__DeleteNoticeItem(_ns1__DeleteNoticeItem *ns1__DeleteNoticeItem, _ns1__DeleteNoticeItemResponse *ns1__DeleteNoticeItemResponse) { return soap ? soap_call___ns7__DeleteNoticeItem(soap, endpoint, NULL, ns1__DeleteNoticeItem, ns1__DeleteNoticeItemResponse) : SOAP_EOM; };
	/// Invoke 'InserNoticeToSomeOne' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__InserNoticeToSomeOne(_ns1__InserNoticeToSomeOne *ns1__InserNoticeToSomeOne, _ns1__InserNoticeToSomeOneResponse *ns1__InserNoticeToSomeOneResponse) { return soap ? soap_call___ns7__InserNoticeToSomeOne(soap, endpoint, NULL, ns1__InserNoticeToSomeOne, ns1__InserNoticeToSomeOneResponse) : SOAP_EOM; };
	/// Invoke 'GetReturnProportionRecord' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetReturnProportionRecord(_ns1__GetReturnProportionRecord *ns1__GetReturnProportionRecord, _ns1__GetReturnProportionRecordResponse *ns1__GetReturnProportionRecordResponse) { return soap ? soap_call___ns7__GetReturnProportionRecord(soap, endpoint, NULL, ns1__GetReturnProportionRecord, ns1__GetReturnProportionRecordResponse) : SOAP_EOM; };
	/// Invoke 'AddtReturnProportion' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__AddtReturnProportion(_ns1__AddtReturnProportion *ns1__AddtReturnProportion, _ns1__AddtReturnProportionResponse *ns1__AddtReturnProportionResponse) { return soap ? soap_call___ns7__AddtReturnProportion(soap, endpoint, NULL, ns1__AddtReturnProportion, ns1__AddtReturnProportionResponse) : SOAP_EOM; };
	/// Invoke 'UpdatetReturnProportion' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__UpdatetReturnProportion(_ns1__UpdatetReturnProportion *ns1__UpdatetReturnProportion, _ns1__UpdatetReturnProportionResponse *ns1__UpdatetReturnProportionResponse) { return soap ? soap_call___ns7__UpdatetReturnProportion(soap, endpoint, NULL, ns1__UpdatetReturnProportion, ns1__UpdatetReturnProportionResponse) : SOAP_EOM; };
	/// Invoke 'DeletetReturnProportion' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__DeletetReturnProportion(_ns1__DeletetReturnProportion *ns1__DeletetReturnProportion, _ns1__DeletetReturnProportionResponse *ns1__DeletetReturnProportionResponse) { return soap ? soap_call___ns7__DeletetReturnProportion(soap, endpoint, NULL, ns1__DeletetReturnProportion, ns1__DeletetReturnProportionResponse) : SOAP_EOM; };
	/// Invoke 'GetPhoneNumberBelongByCondition' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetPhoneNumberBelongByCondition(_ns1__GetPhoneNumberBelongByCondition *ns1__GetPhoneNumberBelongByCondition, _ns1__GetPhoneNumberBelongByConditionResponse *ns1__GetPhoneNumberBelongByConditionResponse) { return soap ? soap_call___ns7__GetPhoneNumberBelongByCondition(soap, endpoint, NULL, ns1__GetPhoneNumberBelongByCondition, ns1__GetPhoneNumberBelongByConditionResponse) : SOAP_EOM; };
	/// Invoke 'UpdatePhoneNumberBelong' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__UpdatePhoneNumberBelong(_ns1__UpdatePhoneNumberBelong *ns1__UpdatePhoneNumberBelong, _ns1__UpdatePhoneNumberBelongResponse *ns1__UpdatePhoneNumberBelongResponse) { return soap ? soap_call___ns7__UpdatePhoneNumberBelong(soap, endpoint, NULL, ns1__UpdatePhoneNumberBelong, ns1__UpdatePhoneNumberBelongResponse) : SOAP_EOM; };
	/// Invoke 'AddPhoneNumberBelong' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__AddPhoneNumberBelong(_ns1__AddPhoneNumberBelong *ns1__AddPhoneNumberBelong, _ns1__AddPhoneNumberBelongResponse *ns1__AddPhoneNumberBelongResponse) { return soap ? soap_call___ns7__AddPhoneNumberBelong(soap, endpoint, NULL, ns1__AddPhoneNumberBelong, ns1__AddPhoneNumberBelongResponse) : SOAP_EOM; };
	/// Invoke 'DeletePhoneNumberBelong' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__DeletePhoneNumberBelong(_ns1__DeletePhoneNumberBelong *ns1__DeletePhoneNumberBelong, _ns1__DeletePhoneNumberBelongResponse *ns1__DeletePhoneNumberBelongResponse) { return soap ? soap_call___ns7__DeletePhoneNumberBelong(soap, endpoint, NULL, ns1__DeletePhoneNumberBelong, ns1__DeletePhoneNumberBelongResponse) : SOAP_EOM; };
	/// Invoke 'GetCompanyInfo' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetCompanyInfo(_ns1__GetCompanyInfo *ns1__GetCompanyInfo, _ns1__GetCompanyInfoResponse *ns1__GetCompanyInfoResponse) { return soap ? soap_call___ns7__GetCompanyInfo(soap, endpoint, NULL, ns1__GetCompanyInfo, ns1__GetCompanyInfoResponse) : SOAP_EOM; };
	/// Invoke 'UpdateCompanyInfo' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__UpdateCompanyInfo(_ns1__UpdateCompanyInfo *ns1__UpdateCompanyInfo, _ns1__UpdateCompanyInfoResponse *ns1__UpdateCompanyInfoResponse) { return soap ? soap_call___ns7__UpdateCompanyInfo(soap, endpoint, NULL, ns1__UpdateCompanyInfo, ns1__UpdateCompanyInfoResponse) : SOAP_EOM; };
	/// Invoke 'GetCompanyAccount' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetCompanyAccount(_ns1__GetCompanyAccount *ns1__GetCompanyAccount, _ns1__GetCompanyAccountResponse *ns1__GetCompanyAccountResponse) { return soap ? soap_call___ns7__GetCompanyAccount(soap, endpoint, NULL, ns1__GetCompanyAccount, ns1__GetCompanyAccountResponse) : SOAP_EOM; };
	/// Invoke 'AddCompanyAccount' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__AddCompanyAccount(_ns1__AddCompanyAccount *ns1__AddCompanyAccount, _ns1__AddCompanyAccountResponse *ns1__AddCompanyAccountResponse) { return soap ? soap_call___ns7__AddCompanyAccount(soap, endpoint, NULL, ns1__AddCompanyAccount, ns1__AddCompanyAccountResponse) : SOAP_EOM; };
	/// Invoke 'UpdateCompanyAccount' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__UpdateCompanyAccount(_ns1__UpdateCompanyAccount *ns1__UpdateCompanyAccount, _ns1__UpdateCompanyAccountResponse *ns1__UpdateCompanyAccountResponse) { return soap ? soap_call___ns7__UpdateCompanyAccount(soap, endpoint, NULL, ns1__UpdateCompanyAccount, ns1__UpdateCompanyAccountResponse) : SOAP_EOM; };
	/// Invoke 'DeleteCompanyAccount' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__DeleteCompanyAccount(_ns1__DeleteCompanyAccount *ns1__DeleteCompanyAccount, _ns1__DeleteCompanyAccountResponse *ns1__DeleteCompanyAccountResponse) { return soap ? soap_call___ns7__DeleteCompanyAccount(soap, endpoint, NULL, ns1__DeleteCompanyAccount, ns1__DeleteCompanyAccountResponse) : SOAP_EOM; };
	/// Invoke 'GetClientVersion' of service 'UtilFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns7__GetClientVersion(_ns1__GetClientVersion *ns1__GetClientVersion, _ns1__GetClientVersionResponse *ns1__GetClientVersionResponse) { return soap ? soap_call___ns7__GetClientVersion(soap, endpoint, NULL, ns1__GetClientVersion, ns1__GetClientVersionResponse) : SOAP_EOM; };
};
#endif
