/* soapPaymentFunctionWebServiceSoapProxy.h
   Generated by gSOAP 2.8.3 from soapProxy.h

Copyright(C) 2000-2011, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under one of the following licenses:
1) GPL or 2) Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapPaymentFunctionWebServiceSoapProxy_H
#define soapPaymentFunctionWebServiceSoapProxy_H
#include "soapH.h"
class PaymentFunctionWebServiceSoap
{   public:
	/// Runtime engine context allocated in constructor
	struct soap *soap;
	/// Endpoint URL of service 'PaymentFunctionWebServiceSoap' (change as needed)
	const char *endpoint;
	/// Constructor allocates soap engine context, sets default endpoint URL, and sets namespace mapping table
	PaymentFunctionWebServiceSoap()
	{ soap = soap_new(); endpoint = "http://220.165.8.124:2655/PaymentFunctionWebService.asmx"; if (soap && !soap->namespaces) { static const struct Namespace namespaces[] = 
{
	{"SOAP-ENV", "http://schemas.xmlsoap.org/soap/envelope/", "http://www.w3.org/*/soap-envelope", NULL},
	{"SOAP-ENC", "http://schemas.xmlsoap.org/soap/encoding/", "http://www.w3.org/*/soap-encoding", NULL},
	{"xsi", "http://www.w3.org/2001/XMLSchema-instance", "http://www.w3.org/*/XMLSchema-instance", NULL},
	{"xsd", "http://www.w3.org/2001/XMLSchema", "http://www.w3.org/*/XMLSchema", NULL},
	{"ns2", "http://microsoft.com/wsdl/types/", NULL, NULL},
	{"ns10", "http://tempuri.org/HttpServiceSoap12", NULL, NULL},
	{"ns11", "http://tempuri.org/MobileWebServiceSoap", NULL, NULL},
	{"ns12", "http://tempuri.org/MobileWebServiceSoap12", NULL, NULL},
	{"ns13", "http://tempuri.org/BusinessFunctionWebServiceSoap", NULL, NULL},
	{"ns14", "http://tempuri.org/BusinessFunctionWebServiceSoap12", NULL, NULL},
	{"ns3", "http://tempuri.org/PaymentFunctionWebServiceSoap", NULL, NULL},
	{"ns4", "http://tempuri.org/PaymentFunctionWebServiceSoap12", NULL, NULL},
	{"ns5", "http://tempuri.org/UserFunctionWebServiceSoap", NULL, NULL},
	{"ns6", "http://tempuri.org/UserFunctionWebServiceSoap12", NULL, NULL},
	{"ns7", "http://tempuri.org/UtilFunctionWebServiceSoap", NULL, NULL},
	{"ns1", "http://tempuri.org/", NULL, NULL},
	{"ns8", "http://tempuri.org/UtilFunctionWebServiceSoap12", NULL, NULL},
	{"ns9", "http://tempuri.org/HttpServiceSoap", NULL, NULL},
	{NULL, NULL, NULL, NULL}
};
	soap->namespaces = namespaces; } };
	/// Destructor frees deserialized data and soap engine context
	virtual ~PaymentFunctionWebServiceSoap() { if (soap) { soap_destroy(soap); soap_end(soap); soap_free(soap); } };
	/// Invoke 'GetLocation' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetLocation(_ns1__GetLocation *ns1__GetLocation, _ns1__GetLocationResponse *ns1__GetLocationResponse) { return soap ? soap_call___ns3__GetLocation(soap, endpoint, NULL, ns1__GetLocation, ns1__GetLocationResponse) : SOAP_EOM; };
	/// Invoke 'PayMoney' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__PayMoney(_ns1__PayMoney *ns1__PayMoney, _ns1__PayMoneyResponse *ns1__PayMoneyResponse) { return soap ? soap_call___ns3__PayMoney(soap, endpoint, NULL, ns1__PayMoney, ns1__PayMoneyResponse) : SOAP_EOM; };
	/// Invoke 'PayMoneyWithList' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__PayMoneyWithList(_ns1__PayMoneyWithList *ns1__PayMoneyWithList, _ns1__PayMoneyWithListResponse *ns1__PayMoneyWithListResponse) { return soap ? soap_call___ns3__PayMoneyWithList(soap, endpoint, NULL, ns1__PayMoneyWithList, ns1__PayMoneyWithListResponse) : SOAP_EOM; };
	/// Invoke 'RequstRollback' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__RequstRollback(_ns1__RequstRollback *ns1__RequstRollback, _ns1__RequstRollbackResponse *ns1__RequstRollbackResponse) { return soap ? soap_call___ns3__RequstRollback(soap, endpoint, NULL, ns1__RequstRollback, ns1__RequstRollbackResponse) : SOAP_EOM; };
	/// Invoke 'PayInternet' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__PayInternet(_ns1__PayInternet *ns1__PayInternet, _ns1__PayInternetResponse *ns1__PayInternetResponse) { return soap ? soap_call___ns3__PayInternet(soap, endpoint, NULL, ns1__PayInternet, ns1__PayInternetResponse) : SOAP_EOM; };
	/// Invoke 'PayInternetWithList' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__PayInternetWithList(_ns1__PayInternetWithList *ns1__PayInternetWithList, _ns1__PayInternetWithListResponse *ns1__PayInternetWithListResponse) { return soap ? soap_call___ns3__PayInternetWithList(soap, endpoint, NULL, ns1__PayInternetWithList, ns1__PayInternetWithListResponse) : SOAP_EOM; };
	/// Invoke 'RequstInternetRollback' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__RequstInternetRollback(_ns1__RequstInternetRollback *ns1__RequstInternetRollback, _ns1__RequstInternetRollbackResponse *ns1__RequstInternetRollbackResponse) { return soap ? soap_call___ns3__RequstInternetRollback(soap, endpoint, NULL, ns1__RequstInternetRollback, ns1__RequstInternetRollbackResponse) : SOAP_EOM; };
	/// Invoke 'PayGame' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__PayGame(_ns1__PayGame *ns1__PayGame, _ns1__PayGameResponse *ns1__PayGameResponse) { return soap ? soap_call___ns3__PayGame(soap, endpoint, NULL, ns1__PayGame, ns1__PayGameResponse) : SOAP_EOM; };
	/// Invoke 'PayPublicTel' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__PayPublicTel(_ns1__PayPublicTel *ns1__PayPublicTel, _ns1__PayPublicTelResponse *ns1__PayPublicTelResponse) { return soap ? soap_call___ns3__PayPublicTel(soap, endpoint, NULL, ns1__PayPublicTel, ns1__PayPublicTelResponse) : SOAP_EOM; };
	/// Invoke 'GetPaymentRecord' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetPaymentRecord(_ns1__GetPaymentRecord *ns1__GetPaymentRecord, _ns1__GetPaymentRecordResponse *ns1__GetPaymentRecordResponse) { return soap ? soap_call___ns3__GetPaymentRecord(soap, endpoint, NULL, ns1__GetPaymentRecord, ns1__GetPaymentRecordResponse) : SOAP_EOM; };
	/// Invoke 'GetPaymentItem' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetPaymentItem(_ns1__GetPaymentItem *ns1__GetPaymentItem, _ns1__GetPaymentItemResponse *ns1__GetPaymentItemResponse) { return soap ? soap_call___ns3__GetPaymentItem(soap, endpoint, NULL, ns1__GetPaymentItem, ns1__GetPaymentItemResponse) : SOAP_EOM; };
	/// Invoke 'GetTransactionByCondition' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetTransactionByCondition(_ns1__GetTransactionByCondition *ns1__GetTransactionByCondition, _ns1__GetTransactionByConditionResponse *ns1__GetTransactionByConditionResponse) { return soap ? soap_call___ns3__GetTransactionByCondition(soap, endpoint, NULL, ns1__GetTransactionByCondition, ns1__GetTransactionByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetTransactionStaticsByCondition' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetTransactionStaticsByCondition(_ns1__GetTransactionStaticsByCondition *ns1__GetTransactionStaticsByCondition, _ns1__GetTransactionStaticsByConditionResponse *ns1__GetTransactionStaticsByConditionResponse) { return soap ? soap_call___ns3__GetTransactionStaticsByCondition(soap, endpoint, NULL, ns1__GetTransactionStaticsByCondition, ns1__GetTransactionStaticsByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetPaymentOrPaymentHistoryByCondition' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetPaymentOrPaymentHistoryByCondition(_ns1__GetPaymentOrPaymentHistoryByCondition *ns1__GetPaymentOrPaymentHistoryByCondition, _ns1__GetPaymentOrPaymentHistoryByConditionResponse *ns1__GetPaymentOrPaymentHistoryByConditionResponse) { return soap ? soap_call___ns3__GetPaymentOrPaymentHistoryByCondition(soap, endpoint, NULL, ns1__GetPaymentOrPaymentHistoryByCondition, ns1__GetPaymentOrPaymentHistoryByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetPayInternetByCondition' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetPayInternetByCondition(_ns1__GetPayInternetByCondition *ns1__GetPayInternetByCondition, _ns1__GetPayInternetByConditionResponse *ns1__GetPayInternetByConditionResponse) { return soap ? soap_call___ns3__GetPayInternetByCondition(soap, endpoint, NULL, ns1__GetPayInternetByCondition, ns1__GetPayInternetByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetPayInternetHistoryByCondition' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetPayInternetHistoryByCondition(_ns1__GetPayInternetHistoryByCondition *ns1__GetPayInternetHistoryByCondition, _ns1__GetPayInternetHistoryByConditionResponse *ns1__GetPayInternetHistoryByConditionResponse) { return soap ? soap_call___ns3__GetPayInternetHistoryByCondition(soap, endpoint, NULL, ns1__GetPayInternetHistoryByCondition, ns1__GetPayInternetHistoryByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetPayGameByCondition' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetPayGameByCondition(_ns1__GetPayGameByCondition *ns1__GetPayGameByCondition, _ns1__GetPayGameByConditionResponse *ns1__GetPayGameByConditionResponse) { return soap ? soap_call___ns3__GetPayGameByCondition(soap, endpoint, NULL, ns1__GetPayGameByCondition, ns1__GetPayGameByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetPayGameHistoryByCondition' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetPayGameHistoryByCondition(_ns1__GetPayGameHistoryByCondition *ns1__GetPayGameHistoryByCondition, _ns1__GetPayGameHistoryByConditionResponse *ns1__GetPayGameHistoryByConditionResponse) { return soap ? soap_call___ns3__GetPayGameHistoryByCondition(soap, endpoint, NULL, ns1__GetPayGameHistoryByCondition, ns1__GetPayGameHistoryByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetPayPublicTelByCondition' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetPayPublicTelByCondition(_ns1__GetPayPublicTelByCondition *ns1__GetPayPublicTelByCondition, _ns1__GetPayPublicTelByConditionResponse *ns1__GetPayPublicTelByConditionResponse) { return soap ? soap_call___ns3__GetPayPublicTelByCondition(soap, endpoint, NULL, ns1__GetPayPublicTelByCondition, ns1__GetPayPublicTelByConditionResponse) : SOAP_EOM; };
	/// Invoke 'GetPayPublicTelHistoryByCondition' of service 'PaymentFunctionWebServiceSoap' and return error code (or SOAP_OK)
	virtual int __ns3__GetPayPublicTelHistoryByCondition(_ns1__GetPayPublicTelHistoryByCondition *ns1__GetPayPublicTelHistoryByCondition, _ns1__GetPayPublicTelHistoryByConditionResponse *ns1__GetPayPublicTelHistoryByConditionResponse) { return soap ? soap_call___ns3__GetPayPublicTelHistoryByCondition(soap, endpoint, NULL, ns1__GetPayPublicTelHistoryByCondition, ns1__GetPayPublicTelHistoryByConditionResponse) : SOAP_EOM; };
};
#endif
